Product.create!([
  {name: "Intelligent Silk Wallet", price: "3100000.0", image_url: "https://placehold.it/300x300.png", description: "deep dive", amount_in_inventory: nil},
  {name: "Sleek Linen Pants", price: "35.0", image_url: "https://placehold.it/300x300.png", description: "ideate", amount_in_inventory: nil},
  {name: "Mediocre Plastic Wallet", price: "85.0", image_url: "https://placehold.it/300x300.png", description: "streamline", amount_in_inventory: nil},
  {name: "Ergonomic Silk Car", price: "75.0", image_url: "https://placehold.it/300x300.png", description: "t-shirt sizes", amount_in_inventory: nil},
  {name: "Durable Bronze Bench", price: "64.0", image_url: "https://placehold.it/300x300.png", description: "snackable content", amount_in_inventory: nil},
  {name: "Small Rubber Car", price: "59.0", image_url: "https://placehold.it/300x300.png", description: "thought leadership", amount_in_inventory: nil},
  {name: "Practical Copper Keyboard", price: "72.0", image_url: "https://placehold.it/300x300.png", description: "granular", amount_in_inventory: nil},
  {name: "Lightweight Leather Knife", price: "49.0", image_url: "https://placehold.it/300x300.png", description: "expansion play", amount_in_inventory: nil},
  {name: "Practical Leather Bench", price: "78.0", image_url: "https://placehold.it/300x300.png", description: "out of pocket", amount_in_inventory: nil},
  {name: "Gorgeous Concrete Computer", price: "72.0", image_url: "https://placehold.it/300x300.png", description: "branding", amount_in_inventory: nil},
  {name: "Sleek Linen Shirt", price: "87.0", image_url: "https://placehold.it/300x300.png", description: "deep dive", amount_in_inventory: nil},
  {name: "Rustic Iron Lamp", price: "74.0", image_url: "https://placehold.it/300x300.png", description: "gamification", amount_in_inventory: nil},
  {name: "Gorgeous Paper Computer", price: "73.0", image_url: "https://placehold.it/300x300.png", description: "rubber meets the road", amount_in_inventory: nil},
  {name: "Fantastic Aluminum Knife", price: "54.0", image_url: "https://placehold.it/300x300.png", description: "out of the box", amount_in_inventory: nil},
  {name: "Durable Rubber Pants", price: "38.0", image_url: "https://placehold.it/300x300.png", description: "agile marketing", amount_in_inventory: nil},
  {name: "Incredible Bronze Knife", price: "71.0", image_url: "https://placehold.it/300x300.png", description: "branding", amount_in_inventory: nil},
  {name: "Small Wool Shoes", price: "54.0", image_url: "https://placehold.it/300x300.png", description: "thought leadership", amount_in_inventory: nil},
  {name: "Gorgeous Steel Lamp", price: "0.0", image_url: "https://placehold.it/300x300.png", description: "learnings", amount_in_inventory: nil},
  {name: "Awesome Concrete Shoes", price: "30.0", image_url: "https://placehold.it/300x300.png", description: "expansion play", amount_in_inventory: nil},
  {name: "Intelligent Wool Bench", price: "5.0", image_url: "https://placehold.it/300x300.png", description: "value proposition", amount_in_inventory: nil},
  {name: "Intelligent Steel Bag", price: "7.0", image_url: "https://placehold.it/300x300.png", description: "branding", amount_in_inventory: nil},
  {name: "Enormous Wool Bench", price: "86.0", image_url: "https://placehold.it/300x300.png", description: "immersive experience", amount_in_inventory: nil},
  {name: "Fantastic Wool Wallet", price: "46.0", image_url: "https://placehold.it/300x300.png", description: "had to 'punt' on that", amount_in_inventory: nil},
  {name: "Gorgeous Iron Hat", price: "49.0", image_url: "https://placehold.it/300x300.png", description: "impact map", amount_in_inventory: nil},
  {name: "Sleek Silk Computer", price: "4.0", image_url: "https://placehold.it/300x300.png", description: "circle back", amount_in_inventory: nil},
  {name: "Incredible Granite Clock", price: "83.0", image_url: "https://placehold.it/300x300.png", description: "data points", amount_in_inventory: nil},
  {name: "Aerodynamic Bronze Clock", price: "75.0", image_url: "https://placehold.it/300x300.png", description: "deep dive", amount_in_inventory: nil},
  {name: "Aerodynamic Rubber Knife", price: "45.0", image_url: "https://placehold.it/300x300.png", description: "penetrate the market", amount_in_inventory: nil},
  {name: "Enormous Silk Coat", price: "2.0", image_url: "https://placehold.it/300x300.png", description: "learnings", amount_in_inventory: nil},
  {name: "Intelligent Wooden Computer", price: "76.0", image_url: "https://placehold.it/300x300.png", description: "synergy", amount_in_inventory: nil},
  {name: "Aerodynamic Iron Bag", price: "82.0", image_url: "https://placehold.it/300x300.png", description: "impact map", amount_in_inventory: nil},
  {name: "Durable Aluminum Keyboard", price: "93.0", image_url: "https://placehold.it/300x300.png", description: "plug and chug", amount_in_inventory: nil},
  {name: "Gorgeous Copper Car", price: "72.0", image_url: "https://placehold.it/300x300.png", description: "market share", amount_in_inventory: nil},
  {name: "Rustic Wool Clock", price: "70.0", image_url: "https://placehold.it/300x300.png", description: "best practice", amount_in_inventory: nil},
  {name: "Durable Leather Table", price: "67.0", image_url: "https://placehold.it/300x300.png", description: "synergy", amount_in_inventory: nil},
  {name: "Incredible Linen Lamp", price: "21.0", image_url: "https://placehold.it/300x300.png", description: "out of the box", amount_in_inventory: nil},
  {name: "Aerodynamic Paper Hat", price: "93.0", image_url: "https://placehold.it/300x300.png", description: "deep dive", amount_in_inventory: nil},
  {name: "Intelligent Cotton Gloves", price: "91.0", image_url: "https://placehold.it/300x300.png", description: "bleeding edge", amount_in_inventory: nil},
  {name: "Enormous Bronze Keyboard", price: "39.0", image_url: "https://placehold.it/300x300.png", description: "sprint to the finish line", amount_in_inventory: nil},
  {name: "Awesome Steel Gloves", price: "33.0", image_url: "https://placehold.it/300x300.png", description: "bleeding edge", amount_in_inventory: nil},
  {name: "Rustic Granite Clock", price: "74.0", image_url: "https://placehold.it/300x300.png", description: "get a pulse on", amount_in_inventory: nil},
  {name: "Durable Bronze Shirt", price: "23.0", image_url: "https://placehold.it/300x300.png", description: "bleeding edge", amount_in_inventory: nil},
  {name: "Awesome Marble Coat", price: "98.0", image_url: "https://placehold.it/300x300.png", description: "had to 'punt' on that", amount_in_inventory: nil},
  {name: "Intelligent Leather Shoes", price: "15.0", image_url: "https://placehold.it/300x300.png", description: "tee it up", amount_in_inventory: nil},
  {name: "Synergistic Plastic Plate", price: "19.0", image_url: "https://placehold.it/300x300.png", description: "customer journey", amount_in_inventory: nil},
  {name: "Enormous Wool Gloves", price: "51.0", image_url: "https://placehold.it/300x300.png", description: "put a bow on it", amount_in_inventory: nil},
  {name: "Fantastic Granite Watch", price: "67.0", image_url: "https://placehold.it/300x300.png", description: "agile marketing", amount_in_inventory: nil},
  {name: "Lightweight Paper Table", price: "92.0", image_url: "https://placehold.it/300x300.png", description: "had to 'punt' on that", amount_in_inventory: nil},
  {name: "Synergistic Concrete Wallet", price: "70.0", image_url: "https://placehold.it/300x300.png", description: "bleeding edge", amount_in_inventory: nil},
  {name: "Intelligent Wool Watch", price: "86.0", image_url: "https://placehold.it/300x300.png", description: "had to 'punt' on that", amount_in_inventory: nil},
  {name: "Aerodynamic Cotton Bench", price: "30.0", image_url: "https://placehold.it/300x300.png", description: "snackable content", amount_in_inventory: nil},
  {name: "Heavy Duty Steel Hat", price: "98.0", image_url: "https://placehold.it/300x300.png", description: "growth unit", amount_in_inventory: nil},
  {name: "Durable Wooden Computer", price: "89.0", image_url: "https://placehold.it/300x300.png", description: "gamification", amount_in_inventory: nil},
  {name: "Synergistic Linen Shirt", price: "73.0", image_url: "https://placehold.it/300x300.png", description: "put a bow on it", amount_in_inventory: nil},
  {name: "Fantastic Leather Pants", price: "82.0", image_url: "https://placehold.it/300x300.png", description: "put a pin in it", amount_in_inventory: nil},
  {name: "Ergonomic Wooden Car", price: "28.0", image_url: "https://placehold.it/300x300.png", description: "immersive experience", amount_in_inventory: nil},
  {name: "Small Granite Chair", price: "31.0", image_url: "https://placehold.it/300x300.png", description: "tee it up", amount_in_inventory: nil},
  {name: "Aerodynamic Linen Pants", price: "69.0", image_url: "https://placehold.it/300x300.png", description: "growth unit", amount_in_inventory: nil},
  {name: "Synergistic Concrete Coat", price: "85.0", image_url: "https://placehold.it/300x300.png", description: "data points", amount_in_inventory: nil},
  {name: "Synergistic Steel Wallet", price: "50.0", image_url: "https://placehold.it/300x300.png", description: "two-way street", amount_in_inventory: nil},
  {name: "Awesome Silk Plate", price: "15.0", image_url: "https://placehold.it/300x300.png", description: "thought leader", amount_in_inventory: nil},
  {name: "Fantastic Wooden Plate", price: "31.0", image_url: "https://placehold.it/300x300.png", description: "SWAG", amount_in_inventory: nil},
  {name: "Rustic Silk Hat", price: "88.0", image_url: "https://placehold.it/300x300.png", description: "synergy", amount_in_inventory: nil},
  {name: "Gorgeous Cotton Clock", price: "25.0", image_url: "https://placehold.it/300x300.png", description: "ideate", amount_in_inventory: nil},
  {name: "Intelligent Wooden Coat", price: "30.0", image_url: "https://placehold.it/300x300.png", description: "out of pocket", amount_in_inventory: nil},
  {name: "Small Wool Table", price: "77.0", image_url: "https://placehold.it/300x300.png", description: "value proposition", amount_in_inventory: nil},
  {name: "Aerodynamic Wooden Hat", price: "94.0", image_url: "https://placehold.it/300x300.png", description: "swim lane", amount_in_inventory: nil},
  {name: "Intelligent Iron Keyboard", price: "99.0", image_url: "https://placehold.it/300x300.png", description: "button up the loose ends", amount_in_inventory: nil},
  {name: "Intelligent Wooden Wallet", price: "13.0", image_url: "https://placehold.it/300x300.png", description: "get a pulse on", amount_in_inventory: nil},
  {name: "Synergistic Copper Knife", price: "9.0", image_url: "https://placehold.it/300x300.png", description: "expansion play", amount_in_inventory: nil},
  {name: "Incredible Aluminum Watch", price: "68.0", image_url: "https://placehold.it/300x300.png", description: "plug and chug", amount_in_inventory: nil},
  {name: "Aerodynamic Granite Coat", price: "72.0", image_url: "https://placehold.it/300x300.png", description: "penetrate the market", amount_in_inventory: nil},
  {name: "Ergonomic Cotton Chair", price: "5.0", image_url: "https://placehold.it/300x300.png", description: "deep dive", amount_in_inventory: nil},
  {name: "Rustic Plastic Bench", price: "9.0", image_url: "https://placehold.it/300x300.png", description: "streamline", amount_in_inventory: nil},
  {name: "Durable Wooden Computer", price: "35.0", image_url: "https://placehold.it/300x300.png", description: "had to 'punt' on that", amount_in_inventory: nil},
  {name: "Gorgeous Wooden Shoes", price: "54.0", image_url: "https://placehold.it/300x300.png", description: "put a bow on it", amount_in_inventory: nil},
  {name: "Rustic Paper Hat", price: "69.0", image_url: "https://placehold.it/300x300.png", description: "SWAG", amount_in_inventory: nil},
  {name: "Sleek Bronze Coat", price: "65.0", image_url: "https://placehold.it/300x300.png", description: "growth unit", amount_in_inventory: nil},
  {name: "Fantastic Granite Clock", price: "45.0", image_url: "https://placehold.it/300x300.png", description: "agile marketing", amount_in_inventory: nil},
  {name: "Aerodynamic Cotton Gloves", price: "63.0", image_url: "https://placehold.it/300x300.png", description: "buying cycle", amount_in_inventory: nil},
  {name: "Lightweight Cotton Knife", price: "7.0", image_url: "https://placehold.it/300x300.png", description: "out of pocket", amount_in_inventory: nil},
  {name: "Intelligent Iron Car", price: "26.0", image_url: "https://placehold.it/300x300.png", description: "learnings", amount_in_inventory: nil},
  {name: "Intelligent Aluminum Bottle", price: "31.0", image_url: "https://placehold.it/300x300.png", description: "etc. etc.", amount_in_inventory: nil},
  {name: "Intelligent Concrete Chair", price: "70.0", image_url: "https://placehold.it/300x300.png", description: "immersive experience", amount_in_inventory: nil},
  {name: "Heavy Duty Leather Shoes", price: "41.0", image_url: "https://placehold.it/300x300.png", description: "out of pocket", amount_in_inventory: nil},
  {name: "Fantastic Concrete Knife", price: "32.0", image_url: "https://placehold.it/300x300.png", description: "bleeding edge", amount_in_inventory: nil},
  {name: "Durable Aluminum Car", price: "95.0", image_url: "https://placehold.it/300x300.png", description: "etc. etc.", amount_in_inventory: nil},
  {name: "Lightweight Paper Coat", price: "87.0", image_url: "https://placehold.it/300x300.png", description: "branding", amount_in_inventory: nil},
  {name: "Awesome Granite Clock", price: "11.0", image_url: "https://placehold.it/300x300.png", description: "market share", amount_in_inventory: nil},
  {name: "Heavy Duty Paper Wallet", price: "64.0", image_url: "https://placehold.it/300x300.png", description: "customer journey", amount_in_inventory: nil},
  {name: "Sleek Marble Table", price: "60.0", image_url: "https://placehold.it/300x300.png", description: "value proposition", amount_in_inventory: nil},
  {name: "Heavy Duty Iron Gloves", price: "77.0", image_url: "https://placehold.it/300x300.png", description: "bandwidth-constrained", amount_in_inventory: nil},
  {name: "Synergistic Plastic Keyboard", price: "47.0", image_url: "https://placehold.it/300x300.png", description: "swim lane", amount_in_inventory: nil},
  {name: "Small Copper Clock", price: "18.0", image_url: "https://placehold.it/300x300.png", description: "immersive experience", amount_in_inventory: nil},
  {name: "Enormous Wooden Gloves", price: "40.0", image_url: "https://placehold.it/300x300.png", description: "bleeding edge", amount_in_inventory: nil},
  {name: "Rustic Steel Watch", price: "37.0", image_url: "https://placehold.it/300x300.png", description: "value add", amount_in_inventory: nil},
  {name: "Fantastic Cotton Clock", price: "13.0", image_url: "https://placehold.it/300x300.png", description: "customer journey", amount_in_inventory: nil},
  {name: "Small Cotton Pants", price: "96.0", image_url: "https://placehold.it/300x300.png", description: "learnings", amount_in_inventory: nil}
])
